version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  orders:
    build: ./services/orders
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka
    ports:
      - "5002:5002"

  billing:
    build: ./services/billing
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka

  notifications:
    build: ./services/notifications
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka
